version: '3.5'

services:
  dictionary-db:
    container_name: dictionary-db
    image: postgres
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      retries: 3
      start_period: 5s
    networks:
      - dictionary
    restart: unless-stopped

  dictionary:
    container_name: dictionary-container
    build: .
    ports:
      - "8080:8080"
    depends_on:
      dictionary-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - dictionary

networks:
  dictionary:
    driver: bridge

volumes:
  postgres:
